<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <div id="form">
        <fieldset>
            <form action="/aeskaeno/public/index/cadastrar" method="post">
                Cadastro de Funcionários
                <p>
                    <label>
                        Nome:<br />
                        <input type="text" name="nome"/>
                    </label>
                </p>
                <p>
                    <label>
                        Cargo:<br />
                        <input type="text" name="cargo"/>
                    </label>
                </p>
                <p>
                    <label>
                        Salário:<br />
                        <input type="text" name="salario"/>
                    </label>
                </p>
                <p>

                        <input type="submit" value="Enviar"/>

                </p>
            </form>
        </fieldset>
    </div>
</body>
</html>