<button class="citricas">Citricas</button>
<button class="fibrosas">Fibrosas</button>
<button class="leitosas">Leitosas</button>
<div class="container"></div>


<script type="text/javascript">

    $(function(){
        $('button').click(function(){
            var grupo = $(this).attr('class');
            $.ajax({
                url : '/aeskaeno/public/index/listarAjax/tipo/'+grupo,
                success : function(data){
                    $('.container').empty().append('<h1>'+grupo.toUpperCase()+'</h1>').css('textAlign','center');
                    for(fruta in data = eval(data)){
                        $('.container').append('<p>'+data[fruta]+'</p>')
                         .css({
                                'color'         : 'blue',
                                'width'         : '200px',
                                'height'        : '100px',
                                'position'      : 'fixed',
                                'marginLeft'    : '-100px',
                                'left'          : '50%'
                         });
                    }
                }
            });
        });
    });

</script>
